ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|

  # Use this file to create a base box for the pgweb and bftest machines.
  # That way you don't have to keep running all the package installs.

  # To do this, do:
  #     vagrant up
  #     vagrant package --output bfbase.box
  #     vagrant box add --name bfbase bfbase.box
  #     vagrant destroy -f
  #     rm -rf bfbase.box .vagrant
  
  config.vm.box = "debian/contrib-stretch64"
  config.vm.provision "shell", path: "../base_provision.sh"
  config.vm.provision "shell", inline: "apt-get install -y sshfs"
  config.vm.provision "shell", inline: "touch /etc/box_is_bfbase; apt-get clean"
end
